server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:uco-db
    username: sa
    password:
    driver-class-name: org.h2.Driver